# Generated by Django 2.2.6 on 2019-10-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_bookmark_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='publishedAt',
            field=models.CharField(max_length=500),
        ),
    ]
