# Generated by Django 2.2.6 on 2019-10-21 08:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_story_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storycard',
            name='card_data',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
