# Generated by Django 2.2.6 on 2019-10-21 11:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191021_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storycard',
            name='card_data',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Write your story'),
        ),
    ]
