# Generated by Django 2.2.6 on 2019-10-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191021_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storycard',
            name='card_data',
            field=models.TextField(verbose_name='Write your story'),
        ),
    ]
